//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinimaServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocVienKhoaHoc
    {
        public string MaKhoaHoc { get; set; }
        public string TaiKhoan { get; set; }
        public Nullable<System.DateTime> NgayGhiDanh { get; set; }
    
        public virtual KhoaHoc KhoaHoc { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
