//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinimaServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int ID { get; set; }
        public int CustomerId { get; set; }
        public int StockId { get; set; }
        public System.DateTime RentalDate { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public string Status { get; set; }
        public string GroupID { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
