//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinimaServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seat()
        {
            this.CinimaBookings = new HashSet<CinimaBooking>();
        }
    
        public string SeatID { get; set; }
        public string SeatName { get; set; }
        public string SeatType { get; set; }
        public string CinimaRoomID { get; set; }
        public Nullable<int> NumOrder { get; set; }
        public string GroupID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CinimaBooking> CinimaBookings { get; set; }
        public virtual CinimaRoom CinimaRoom { get; set; }
    }
}
