//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinimaServer.Models.DBMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public string MaDanhMuc { get; set; }
        public string TenDanhMuc { get; set; }
        public string HinhAnh { get; set; }
        public string DanhSachMonAn { get; set; }
    }
}
