//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinimaServer.Models.dbSinhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public string MaSV { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string SoDT { get; set; }
        public string CMND { get; set; }
        public Nullable<int> DiemToan { get; set; }
        public Nullable<int> DiemLy { get; set; }
        public Nullable<int> DiemHoa { get; set; }
    }
}
