//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinimaServer.Models.QLNV
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int maNhanVien { get; set; }
        public string tenNhanVien { get; set; }
        public string chucVu { get; set; }
        public Nullable<int> heSoChucVu { get; set; }
        public Nullable<decimal> luongCoBan { get; set; }
        public Nullable<decimal> soGioLamTrongThang { get; set; }
    }
}
