//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinimaServer.Models.Task
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public string taskName { get; set; }
        public Nullable<bool> status { get; set; }
        public string alias { get; set; }
    }
}
